replicaCount: 1

image:
  repository: ghcr.io/nervix-io/nervix-k8s-operator
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podAnnotations: {}
podLabels: {}

logFilter: info,nervix_k8s_operator=debug

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL

priorityClassName: ""

extraEnv: []

extraArgs: []
